### ISSUE TITLE
Error in generating boolean literal in ruby

### ISSUE THREAD

**Issue by jzjsuper** [alehander42/pseudo#11]
test.py:
```python
a = True
b = False
```
Generate `test.rb` by executing `$ pseudo-python test.py test.rb`

Generated `test.rb`:
```ruby
a = True
b = False
```

Expected `test.rb`:
```ruby
a = true
b = false
```

**Comment by alehander42** [comment]
That was actually a Pseudo-Python bug, thank you!

[Fixed after that commit](https://github.com/alehander42/pseudo-python/commit/dcdcc4c6e8a82332c27b9e5344d3f655bc9e65de)
