### ISSUE TITLE
JSTranslator doesn't have a String#include? method

### ISSUE THREAD

**Issue by notzoom** [alehander42/pseudo#20]
Trying to translate this Python program to JS:
```
string = "test"

if "test" in string:
   print("positive")

```
What I get is:
Pseudo error:
JSTranslator doesn't have a String#include? method

**Comment by alehander42** [comment]
Pseudo basically needs a weekend or two of work to completely implement and test the standard library of methods (started in https://github.com/alehander42/pseudo/blob/master/docs/library_reference.md).

Do you have an intended usage for it, or you are just interested to experiment?
