### ISSUE TITLE
can't change the type of variable string in global scope from String to List[String]

### ISSUE THREAD

**Issue by notzoom** [alehander42/pseudo#21]
Trying to translate this Python program to JS:

```
string = "I am fine"

string = string.split(" ")

string = string[0]
```
What I get is:
can't change the type of variable string in global scope  from String to List[String]

**Comment by alehander42** [comment]
That's intended.

```python
s = "I am fine"
l = s.split(" ")
s = l[0]
print(s)
```
works

Pseudo translates only a limited subset of Python which is statically typed.
You don't write any types, because it has full type inference, but changing the type of a variable is forbidden
